language: java

env:
  global:
    - SONATYPE_USERNAME=80ymBYBJ
    - secure: "fWNpQtw34CGKtdzBHpawA7dQSMVQg+wg+S7lj6DtAEGJIipSPk5Uod2DYEV+\nSsP9j9yn7VAwbdo8GGqUrS0FNqKctsc6k4COOw3JMAmQEo6HEvwf7aRy/R6x\n9RgMT2YAwC34NStAC/liJunc/4a7L+QHoikr2CFImbrUn4I5+/4="

install: "mvn -DskipTests -U -B install"

after_success:
  - python .travis-addServer.py
  # No need to run clean or run tests when simply deploying.
  - mvn -DskipTests -B --settings ~/.m2/mySettings.xml deploy
